# Geographic bounding box: [lon_min, lat_min, lon_max, lat_max]
bbox: [-124.749582, 32.450970, -116.860294, 41.852115]

# Temporal range for data query
start: 2010-04-01
end: 2010-04-02

# Output directory for downloaded and processed data
out: MERIS_downloads

